### ISSUE TITLE
FID issue: 'tensorflow._api.v2.image' has no attribute 'resize_bilinear'"

### ISSUE THREAD

**Issue by csyanbin** [sh4174/3DStyleGAN#1]
Hi, thanks for sharing this wonderful repo for 3DStyleGAN. 

When running this code, I encountered the problem: "AttributeError: module 'tensorflow._api.v2.image' has no attribute 'resize_bilinear'".
Do you have any idea how to solve this issue?

**Comment by sh4174** [comment]
Hi, 

Thank you for your interest on our repo. I believe it is the TF version issue. I think the easiest way is to install the TF 2.4 version that we used for the test. Or you can change the the resize_bilinear in the code to tf.compat.v1.image.resize_bilinear or tf.image.resize. 

Thanks,
Sungmin

**Comment by csyanbin** [comment]
Hi Sungmin, thanks for the reply!
I have installed the dependencies TF2.4 from the conda_env in this repo. 

Bellow is the error message. 
```
Tensor("Gs/G_synthesis/images_out:0", shape=(?, 1, 256, 256, 32), dtype=float16)
Traceback (most recent call last):
  File "run_training.py", line 641, in <module>
    main()
  File "run_training.py", line 636, in main
    run(**vars(args))
  File "run_training.py", line 565, in run
    dnnlib.submit_run(**kwargs)
  File "/group/pgh001/yliu/code/3DStyleGAN/dnnlib/submission/submit.py", line 343, in submit_run
    return farm.submit(submit_config, host_run_dir)
  File "/group/pgh001/yliu/code/3DStyleGAN/dnnlib/submission/internal/local.py", line 22, in submit
    return run_wrapper(submit_config)
  File "/group/pgh001/yliu/code/3DStyleGAN/dnnlib/submission/submit.py", line 280, in run_wrapper
    run_func_obj(**submit_config.run_func_kwargs)
  File "/group/pgh001/yliu/code/3DStyleGAN/training/training_loop_3d.py", line 450, in training_loop
    metrics.run(pkl, run_dir=dnnlib.make_run_dir_path(), data_dir=dnnlib.convert_path(data_dir), num_gpus=num_gpus, tf_config=tf_config)
  File "/group/pgh001/yliu/code/3DStyleGAN/metrics/metric_base.py", line 235, in run
    metric.run(*args, **kwargs)
  File "/group/pgh001/yliu/code/3DStyleGAN/metrics/metric_base.py", line 68, in run
    self._evaluate(Gs, Gs_kwargs=Gs_kwargs, num_gpus=num_gpus)
  File "/group/pgh001/yliu/code/3DStyleGAN/metrics/frechet_inception_distance_test.py", line 27, in _evaluate
    inception = misc.load_pkl('http://d36zk2xti64re0.cloudfront.net/stylegan1/networks/metrics/inception_v3_features.pkl')
  File "/group/pgh001/yliu/code/3DStyleGAN/training/misc.py", line 27, in load_pkl
    return pickle.load(file, encoding='latin1')
  File "/group/pgh001/yliu/code/3DStyleGAN/dnnlib/tflib/network.py", line 299, in __setstate__
    self._init_graph()
  File "/group/pgh001/yliu/code/3DStyleGAN/dnnlib/tflib/network.py", line 156, in _init_graph
    out_expr = self._build_func(*self.input_templates, **build_kwargs)
  File "<string>", line 350, in inception_v3
AttributeError: module 'tensorflow._api.v2.image' has no attribute 'resize_bilinear'
```

Do you have any specific configuration for the FID computation on TF2.4?
